#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Nov 13 15:30:04 +0800 2021
# SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_4 processing_system7_vip_v1_0_6 lib_cdc_v1_0_2 lib_pkg_v1_0_2 fifo_generator_v13_2_3 lib_fifo_v1_0_12 blk_mem_gen_v8_4_2 lib_bmg_v1_0_11 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_20 axi_vdma_v6_3_6 v_vid_in_axi4s_v4_0_9 axi_lite_ipif_v3_0_4 v_tc_v6_1_13 v_axi4s_vid_out_v4_0_10 proc_sys_reset_v5_0_13 util_vector_logic_v2_0_1 xlconstant_v1_1_5 smartconnect_v1_0 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_18 axi_data_fifo_v2_1_17 axi_crossbar_v2_1_19 xlconcat_v2_1_1 xbip_utils_v3_0_9 axi_utils_v2_0_5 xbip_pipe_v3_0_5 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_5 xbip_dsp48_multadd_v3_0_5 xbip_bram18k_v3_0_5 mult_gen_v12_0_14 floating_point_v7_1_7 axi_protocol_converter_v2_1_18)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2018.3 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "E:/vivado2018_3/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "E:/vivado2018_3/Vivado/2018.3/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "E:/vivado2018_3/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "E:/vivado2018_3/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_4 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/98af/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_6 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_processing_system7_0_0/sim/system_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/64f4/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_3 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/64f4/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/64f4/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_12 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/544a/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/37c2/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_11 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/556c/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_20 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/dfb3/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_6 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_vdma_0_0/sim/system_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_v_vid_in_axi4s_0_0/sim/system_v_vid_in_axi4s_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/a92c/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_axi4s_vid_out_v4_0_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/a87e/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_v_axi4s_vid_out_0_0/sim/system_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_v_tc_0_0/sim/system_v_tc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_proc_sys_reset_0_0/sim/system_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../bd/system/ipshared/2094/DVITransmitter.vhd" \
    "$ref_dir/../../../bd/system/ipshared/2094/SerializerN_1.vhd" \
    "$ref_dir/../../../bd/system/ipshared/2094/TMDSEncoder.vhd" \
    "$ref_dir/../../../bd/system/ipshared/2094/hdmi_tx.vhd" \
    "$ref_dir/../../../bd/system/ip/system_HDMI_FPGA_ML_0_0/sim/system_HDMI_FPGA_ML_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_util_vector_logic_0_0/sim/system_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/sim/bd_919a.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/4649/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_919a_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_919a_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_919a_arsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_919a_rsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_919a_awsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_919a_wsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_919a_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/f85e/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_919a_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_919a_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/9ade/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_919a_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_919a_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_919a_sarn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_919a_srn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_919a_s01mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_919a_s01tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_919a_s01sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_919a_s01a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_919a_sawn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_919a_swn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_919a_sbn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_919a_s02mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_919a_s02tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_919a_s02sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_919a_s02a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_919a_sarn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_919a_srn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_919a_s03mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_919a_s03tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_919a_s03sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_919a_s03a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_919a_sawn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_919a_swn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_919a_sbn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_919a_s04mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_919a_s04tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_919a_s04sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_36/sim/bd_919a_s04a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_37/sim/bd_919a_sarn_2.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_38/sim/bd_919a_srn_2.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_39/sim/bd_919a_s05mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_40/sim/bd_919a_s05tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_41/sim/bd_919a_s05sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_42/sim/bd_919a_s05a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_43/sim/bd_919a_sawn_2.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_44/sim/bd_919a_swn_2.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_45/sim/bd_919a_sbn_2.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_46/sim/bd_919a_m00s2a_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_47/sim/bd_919a_m00arn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_48/sim/bd_919a_m00rn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_49/sim/bd_919a_m00awn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_50/sim/bd_919a_m00wn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_51/sim/bd_919a_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b387/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_52/sim/bd_919a_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/sim/system_smartconnect_0_0.v" \
    "$ref_dir/../../../bd/system/ip/HDMI_INPUT_debug/base_version/hdmi_input_prj/hdmi_input_prj.srcs/sources_1/ip/uicfg7611_0/ui7611reg.v" \
    "$ref_dir/../../../bd/system/ip/HDMI_INPUT_debug/base_version/hdmi_input_prj/hdmi_input_prj.srcs/sources_1/ip/uicfg7611_0/uii2c.v" \
    "$ref_dir/../../../bd/system/ip/HDMI_INPUT_debug/base_version/hdmi_input_prj/hdmi_input_prj.srcs/sources_1/ip/uicfg7611_0/uicfg7611.v" \
    "$ref_dir/../../../bd/system/ip/HDMI_INPUT_debug/base_version/hdmi_input_prj/hdmi_input_prj.srcs/sources_1/ip/uicfg7611_0/sim/uicfg7611_0.v" \
    "$ref_dir/../../../bd/system/ip/HDMI_INPUT_debug/base_version/hdmi_input_prj/hdmi_input_prj.srcs/sources_1/ip/uidelay_0/uidelay.v" \
    "$ref_dir/../../../bd/system/ip/HDMI_INPUT_debug/base_version/hdmi_input_prj/hdmi_input_prj.srcs/sources_1/ip/uidelay_0/sim/uidelay_0.v" \
    "$ref_dir/../../../bd/system/ipshared/HDMI_INPUT_debug/base_version/usr_src/HDMI_IN_Test.v" \
    "$ref_dir/../../../bd/system/ip/system_HDMI_IN_Test_0_0/sim/system_HDMI_IN_Test_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/cc23/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/c4fd/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/6c9d/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_vdma_1_0/sim/system_axi_vdma_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_util_vector_logic_1_0/sim/system_util_vector_logic_1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_util_vector_logic_1_1/sim/system_util_vector_logic_1_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlconcat_0_0/sim/system_xlconcat_0_0.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/9896/hdl/verilog/inner_ctrl_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/9896/hdl/verilog/inner_ctrl.v" \
    "$ref_dir/../../../bd/system/ip/system_inner_ctrl_0_0/sim/system_inner_ctrl_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_video_concat_0_0/sim/system_video_concat_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_video_divide_0_0/sim/system_video_divide_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_xlconstant_0_0/sim/system_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_Key_Debounce_0_0/sim/system_Key_Debounce_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_Key_Debounce_0_1/sim/system_Key_Debounce_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/0da8/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_5 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec8e/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/442e/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/a04b/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b226/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/c08f/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/6bb5/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_1_7 $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/c63e/hdl/floating_point_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/AXIvideo2Mat.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/Block_Mat_exit1245_p.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/cache_Y_channel.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/Consume.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/CvtColor.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/CvtColor_1.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/fifo_w8_d4_A.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/fifo_w32_d2_A.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/fifo_w32_d5_A.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/Mat2AXIvideo.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/Merge.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/Split.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/start_for_cache_YqcK.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_dlmb6.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_dmlbW.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_dskbM.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_fmfYi.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_fpibs.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_fpjbC.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_macud.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_madEe.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_maeOg.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_mancg.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_maocq.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_mapcA.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_mubkb.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_sihbi.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1_uig8j.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/verilog/yuvProcess_de1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/ip/yuvProcess_de1_ap_dlog_20_full_dsp_64.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/ip/yuvProcess_de1_ap_dmul_3_max_dsp_64.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/ip/yuvProcess_de1_ap_dsub_3_full_dsp_64.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/ip/yuvProcess_de1_ap_fmul_1_max_dsp_32.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/ip/yuvProcess_de1_ap_fpext_0_no_dsp_32.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/ip/yuvProcess_de1_ap_fptrunc_0_no_dsp_64.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/ip/yuvProcess_de1_ap_sitofp_2_no_dsp_32.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/614b/hdl/ip/yuvProcess_de1_ap_uitofp_2_no_dsp_32.vhd" \
    "$ref_dir/../../../bd/system/ip/system_yuvProcess_de1_0_0/sim/system_yuvProcess_de1_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/sim/system.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_vdma_2_0/sim/system_axi_vdma_2_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/7a04/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/58e2/hdl" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"E:/vivado2018_3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/AXIvideo2Mat.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/Block_Mat_exit49_pro.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/deal.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/deal_hist1.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/deal_hist1a.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/deal_hist2.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/deal_img.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/deal_wei.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/deal_weia.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/fifo_w8_d4_A.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/fifo_w32_d2_A.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/fifo_w32_d3_A.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/hls_main_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/hls_main_dadd_64nibs.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/hls_main_ddiv_64njbC.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/hls_main_fadd_32nbkb.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/hls_main_fcmp_32ng8j.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/hls_main_fdiv_32ndEe.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/hls_main_fmul_32ncud.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/hls_main_fpext_32fYi.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/hls_main_fsqrt_32hbi.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/hls_main_mul_mul_mb6.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/hls_main_sitodp_3kbM.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/hls_main_sitodp_3lbW.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/hls_main_sitofp_3eOg.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/Mat2AXIvideo.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/start_for_deal_U0.v" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/verilog/hls_main.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/ip/hls_main_ap_dadd_3_full_dsp_64.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/ip/hls_main_ap_ddiv_29_no_dsp_64.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/ip/hls_main_ap_fadd_2_full_dsp_32.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/ip/hls_main_ap_fcmp_0_no_dsp_32.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/ip/hls_main_ap_fdiv_10_no_dsp_32.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/ip/hls_main_ap_fmul_1_max_dsp_32.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/ip/hls_main_ap_fpext_0_no_dsp_32.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/ip/hls_main_ap_fsqrt_8_no_dsp_32.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/ip/hls_main_ap_sitodp_3_no_dsp_32.vhd" \
    "$ref_dir/../../../../video_ov5640.srcs/sources_1/bd/system/ipshared/e48c/hdl/ip/hls_main_ap_sitofp_2_no_dsp_32.vhd" \
    "$ref_dir/../../../bd/system/ip/system_hls_main_0_0/sim/system_hls_main_0_0.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
